# Uncomment the next line to define a global platform for your project
platform :osx, '10.15'

target 'ModelSupport' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ModelSupport
  pod 'SwiftProtobuf', '~> 1.0'

  pod 'STBImage', :path => '../STBImage'


end
